apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kmohammedkasheef-spec/argocd-gitops-demo.git
    targetRevision: main
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
